name: Docker-Compose-Linux-aarch64
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check out docker/compose
        run: |
          git clone https://github.com/docker/compose.git
      #- name: Check out docker/compose
      #  uses: actions/checkout@v2
      #  with:
      #    repository: docker/compose
      #    path: compose

      - name: Install gh cli and login
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
          gh version
          gh auth login --with-token <<< ${{ secrets.gh_token }}
        # env:
        #   gh_token: ${{ secrets.gh_token }}

      - name: install docker
        uses: docker-practice/actions-setup-docker@master
        # this will run and buildx
        # docker run --rm --privileged ghcr.io/dpsigs/tonistiigi-binfmt:latest --install all

      - name: build docker-compose
        id: build
        run: |
          bash  ${{ secrets.sh_op }} build.sh

      - name: Upload bin directory
        uses: actions/upload-artifact@v2
        if: steps.build.outcome == 'success'
        with:
          name: docker-compose-Linux
          path: /tmp/artifact/
